name: build rust images

on: [ push ]

jobs:

  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust_version: "1.58"
            alias: "stable"
          - rust_version: "1.60"
            alias: "edge"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: build image
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          platforms: linux/amd64
          build-args: RUSTC_VERSION=${{ matrix.rust_version }}
          pull: true
          push: false
          tags: neondatabase/rust:${{ matrix.rust_version }},neondatabase/rust:${{ matrix.alias }}

      - name: push image to dockerhub
        if: |
          github.ref_name == 'main' &&
          github.event_name != 'workflow_dispatch'
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          platforms: linux/amd64
          build-args: RUSTC_VERSION=${{ matrix.rust_version }}
          pull: true
          push: true
          tags: neondatabase/rust:${{ matrix.rust_version }},neondatabase/rust:${{ matrix.alias }}

