name: build rust images

on:
  push:
    branches:
      - 'main'

jobs:

  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: rust-1.58
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          build-args: RUSTC_VERSION=1.58
          pull: true
          push: true
          tags: neondatabase/rust:1.58.1,neondatabase/rust:1.58,neondatabase/rust:stable

      - name: rust-1.60
        uses: docker/build-push-action@v2
        with:
          context: ./rust/
          build-args: RUSTC_VERSION=1.60
          pull: true
          push: true
          tags: neondatabase/rust:1.60.0,neondatabase/rust:1.60,neondatabase/rust:edge
